import ExcelJS from 'exceljs';


type CellAddr = { r: number; c: number };

const COLS = 80; // Wide layout for complex grids
const FONT = 'Calibri';

// Helper to convert column number to letter (1 -> A, 2 -> B, etc.)
function col(n: number): string {
    let s = '';
    while (n > 0) {
        const m = (n - 1) % 26;
        s = String.fromCharCode(65 + m) + s;
        n = Math.floor((n - 1) / 26);
    }
    return s;
}

// Helper to create Excel range string
function range(a: CellAddr, b: CellAddr): string {
    return `${col(a.c)}${a.r}:${col(b.c)}${b.r}`;
}

// Set base worksheet properties
function setSheetBase(ws: ExcelJS.Worksheet) {
    ws.properties.defaultRowHeight = 15;
    ws.views = [{ state: 'normal' }];

    // Default column widths
    for (let i = 1; i <= COLS; i++) ws.getColumn(i).width = 2.5;

    // Print settings
    ws.pageSetup = {
        orientation: 'landscape',
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        paperSize: 9, // A4
        horizontalCentered: true,
        margins: {
            left: 0.25,
            right: 0.25,
            top: 0.75,
            bottom: 0.75,
            header: 0.3,
            footer: 0.3
        }
    };
    ws.headerFooter.oddFooter = '&CGenerated by H.E.A.T. Bot System';
}

// Style a cell with common options
function styleCell(
    cell: ExcelJS.Cell,
    opts: Partial<ExcelJS.Style> & { value?: any } = {}
) {
    if ('value' in opts) cell.value = opts.value;

    cell.font = { name: FONT, size: 11, ...(opts.font || {}) };
    if (opts.alignment) cell.alignment = opts.alignment;
    if (opts.fill) cell.fill = opts.fill;
    if (opts.border) cell.border = opts.border;
    if (opts.numFmt) cell.numFmt = opts.numFmt;
}

// Add confidentiality banner
function addConfidentialBanner(ws: ExcelJS.Worksheet) {
    ws.mergeCells(range({ r: 2, c: 3 }, { r: 3, c: 12 }));
    const cell = ws.getCell('C2');
    styleCell(cell, {
        value: 'FOR INTERNAL USE ONLY\nDO NOT SHARE EXTERNALLY',
        font: { bold: true, size: 14, color: { argb: 'FFFF0000' } },
        alignment: { vertical: 'middle', horizontal: 'center', wrapText: true },
        fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFFFF' } },
        border: {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' }
        }
    });
    ws.getRow(2).height = 30;
}

// Add big title
function addBigTitle(ws: ExcelJS.Worksheet, r: number, line1: string, line2: string) {
    ws.mergeCells(range({ r, c: 3 }, { r: r + 1, c: 12 }));
    const cell = ws.getCell(r, 3);
    styleCell(cell, {
        value: `${line1}\n${line2}`,
        font: { bold: true, size: 16 },
        alignment: { vertical: 'middle', horizontal: 'center', wrapText: true }
    });
    ws.getRow(r).height = 40;
}

// Add standard reference row
function addStandardRow(ws: ExcelJS.Worksheet, r: number, standard: string = 'IEC 63180 Ed. 1') {
    styleCell(ws.getCell(r, 3), { value: 'Standard', font: { bold: true } });
    ws.mergeCells(range({ r, c: 4 }, { r, c: 7 }));
    styleCell(ws.getCell(r, 4), { value: standard });
}

// Add metadata block
function addMetaBlock(
    ws: ExcelJS.Worksheet,
    startRow: number,
    entries: Array<{ label: string; value?: string }>
) {
    entries.forEach((e, idx) => {
        const r = startRow + idx;
        styleCell(ws.getCell(r, 3), { value: e.label, font: { bold: true } });
        ws.mergeCells(range({ r, c: 4 }, { r, c: 10 }));
        styleCell(ws.getCell(r, 4), {
            value: e.value ?? '',
            alignment: { vertical: 'middle', horizontal: 'left' }
        });
    });
}

// Convert polar coordinates to cartesian for grid positioning
function polarToCartesian(angle: number, distance: number): { x: number; y: number } {
    const radians = (angle * Math.PI) / 180;
    return {
        x: distance * Math.cos(radians),
        y: distance * Math.sin(radians)
    };
}

export interface TestMetadata {
    testId: number;
    testName: string;
    sensorId: string;
    hwVersion?: string;
    swVersion?: string;
    mountingHeight?: string;
    testLab?: string;
    testStandard?: string;
    testMethod?: string;
    testChoiceName?: string;
    startTime: Date;
    endTime?: Date;
    operator?: string;
    temperature?: number;
    humidity?: number;
}

export interface BoundaryMeasurement {
    angle: number;
    distance: number | null;
    detected: boolean;
}

export interface TangentialMeasurement {
    angle: number;
    distance: number;
    detected: boolean;
}

export interface RadialMeasurement {
    angle: number;
    distance: number;
    detected: boolean;
    offsetFromBoundary?: number;
}

export class ExcelTemplateService {
    /**
     * Generate complete IEC 63180 Excel report
     */
    static async generateIEC63180Report(
        metadata: TestMetadata,
        boundaryData: BoundaryMeasurement[],
        tangentialData: TangentialMeasurement[],
        radialData: RadialMeasurement[]
    ): Promise<ExcelJS.Workbook> {
        const wb = new ExcelJS.Workbook();
        wb.creator = 'H.E.A.T. Bot System';
        wb.created = new Date();

        // Build all tabs matching professional template
        this.buildOverview(wb, metadata, boundaryData, tangentialData, radialData);
        this.buildTangentialGrid(wb, tangentialData, boundaryData, metadata);
        this.buildTangentialBoundary(wb, boundaryData, metadata);
        this.buildRadial(wb, radialData, metadata);
        this.buildCellCount(wb, tangentialData);

        return wb;
    }

    /**
     * Overview Tab - Summary with test execution table
     */
    private static buildOverview(
        wb: ExcelJS.Workbook,
        metadata: TestMetadata,
        boundaryData: BoundaryMeasurement[],
        tangentialData: TangentialMeasurement[],
        radialData: RadialMeasurement[]
    ) {
        const ws = wb.addWorksheet('Overview');
        setSheetBase(ws);

        // Set specific column widths for overview
        ws.getColumn(1).width = 2;
        ws.getColumn(2).width = 2;
        for (let i = 3; i <= 15; i++) ws.getColumn(i).width = 12;

        addConfidentialBanner(ws);
        addBigTitle(ws, 5, 'PIR SENSOR PERFORMANCE', 'OVERVIEW');
        addStandardRow(ws, 8, metadata.testStandard || 'IEC 63180 Ed. 1');

        // Metadata block
        addMetaBlock(ws, 10, [
            { label: 'Product', value: metadata.sensorId },
            { label: 'Test lab', value: metadata.testLab || 'H.E.A.T. Bot Lab' },
            { label: 'Test method', value: metadata.testMethod || 'Automated robotic testing' },
            { label: 'Description EUT', value: metadata.testChoiceName || 'PIR Motion Sensor' },
            { label: 'HW', value: metadata.hwVersion || 'N/A' },
            { label: 'SW', value: metadata.swVersion || 'N/A' },
            { label: 'Date', value: metadata.startTime.toLocaleDateString() },
            { label: 'Manufacturer', value: 'N/A' },
            { label: 'Product reference', value: metadata.sensorId },
            { label: 'Mounting height', value: metadata.mountingHeight || '2.5 m - 3 m' },
            { label: 'Note', value: `Sample #${metadata.testId} - IEC 63180 Ed. 1` }
        ]);

        // Environmental data
        const summaryRow = 23;
        styleCell(ws.getCell(summaryRow, 3), { value: 'Room temperature', font: { bold: true } });
        styleCell(ws.getCell(summaryRow, 4), {
            value: metadata.temperature ? `${metadata.temperature.toFixed(1)}°C` : 'N/A'
        });

        styleCell(ws.getCell(summaryRow + 1, 3), { value: 'Test person', font: { bold: true } });
        styleCell(ws.getCell(summaryRow + 1, 4), { value: metadata.operator || 'H.E.A.T. Bot' });

        styleCell(ws.getCell(summaryRow + 2, 3), { value: 'Body temperature', font: { bold: true } });
        styleCell(ws.getCell(summaryRow + 2, 4), { value: 'N/A' });

        // Test execution summary table
        const tableStart = 27;

        // Calculate statistics
        const boundaryDetected = boundaryData.filter(b => b.detected).length;
        const tangentialDetected = tangentialData.filter(t => t.detected).length;
        const radialDetected = radialData.filter(r => r.detected).length;

        // Table headers
        styleCell(ws.getCell(tableStart, 3), {
            value: 'TEST EXECUTION',
            font: { bold: true, size: 10 },
            alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } }
        });

        const headers = [
            'TANGENTIAL MOVEMENT BOUNDARY\n2.5 m installation height',
            'TANGENTIAL MOVEMENT BOUNDARY\n3 m installation height',
            'RADIAL MOTION\n2.5 m installation height',
            'RADIAL MOTION\n3 m installation height',
            'RADIAL MOTION\n3 m installation height\nMINOR MOTION - PRESENCE'
        ];

        headers.forEach((header, i) => {
            ws.mergeCells(range({ r: tableStart, c: 4 + i }, { r: tableStart, c: 4 + i }));
            styleCell(ws.getCell(tableStart, 4 + i), {
                value: header,
                font: { bold: true, size: 8 },
                alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
                fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9D9D9' } }
            });
            ws.getRow(tableStart).height = 45;
        });

        // Data rows
        const summaryData = [
            ['TANGENTIAL MOVEMENT BOUNDARY 2.5 m  installation height', boundaryData.length, '-', '-', '-', '-'],
            ['TANGENTIAL MOVEMENT BOUNDARY 3 m  installation height', '-', boundaryData.length, '-', '-', '-'],
            ['RADIAL MOTION 2.5 m  installation height', '-', '-', radialData.length, '-', '-'],
            ['RADIAL MOTION 3 m  installation height', '-', '-', '-', radialData.length, '-']
        ];

        summaryData.forEach((row, i) => {
            row.forEach((val, j) => {
                styleCell(ws.getCell(tableStart + 1 + i, 3 + j), {
                    value: val,
                    font: { size: 9 },
                    alignment: { horizontal: j === 0 ? 'left' : 'center', vertical: 'middle' },
                    border: {
                        top: { style: 'thin' },
                        left: { style: 'thin' },
                        bottom: { style: 'thin' },
                        right: { style: 'thin' }
                    }
                });
            });
        });
    }

    /**
     * Tangential Grid Tab - Detailed grid with actual detection data
     */
    private static buildTangentialGrid(
        wb: ExcelJS.Workbook,
        tangentialData: TangentialMeasurement[],
        boundaryData: BoundaryMeasurement[],
        metadata: TestMetadata
    ) {
        const ws = wb.addWorksheet('Major - Tangential Grid');
        setSheetBase(ws);

        addConfidentialBanner(ws);
        addBigTitle(ws, 5, 'PIR SENSOR PERFORMANCE', 'TANGENTIAL MOTION WITHIN THE DETECTION AREA (Movement 1 m)');

        // Set column widths for grid display
        for (let i = 1; i <= 50; i++) {
            ws.getColumn(i).width = 2.5;
        }

        // Calculation rule note
        ws.mergeCells(range({ r: 8, c: 3 }, { r: 8, c: 20 }));
        styleCell(ws.getCell(8, 3), {
            value: 'Calculation range acc 15 % rule *',
            font: { italic: true, size: 10 },
            alignment: { horizontal: 'left' }
        });

        // Legend
        const legendRow = 10;
        styleCell(ws.getCell(legendRow, 3), { value: 'Grid Plot', font: { bold: true } });
        styleCell(ws.getCell(legendRow + 1, 4), { value: 'Pink Circle is the Boundary Range', font: { size: 9 } });
        styleCell(ws.getCell(legendRow + 2, 4), { value: 'Red Marks = No Detection', font: { size: 9 } });
        styleCell(ws.getCell(legendRow + 3, 4), { value: 'Green marks = Motion Detected', font: { size: 9 } });

        // Color legend samples
        ws.mergeCells(range({ r: legendRow + 2, c: 6 }, { r: legendRow + 2, c: 7 }));
        styleCell(ws.getCell(legendRow + 2, 6), {
            value: '0',
            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFC7CE' } },
            alignment: { horizontal: 'center' }
        });

        ws.mergeCells(range({ r: legendRow + 3, c: 6 }, { r: legendRow + 3, c: 7 }));
        styleCell(ws.getCell(legendRow + 3, 6), {
            value: '1',
            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF92D050' } },
            alignment: { horizontal: 'center' }
        });

        // Group data by distance
        const distanceMap = new Map<number, TangentialMeasurement[]>();
        tangentialData.forEach(t => {
            const dist = Math.round(t.distance);
            if (!distanceMap.has(dist)) distanceMap.set(dist, []);
            distanceMap.get(dist)!.push(t);
        });

        const radii = Array.from(distanceMap.keys()).sort((a, b) => a - b);

        // Create detailed grid for each radius with actual detection data
        let currentRow = 18;
        const gridSize = 33; // Large grid to show detail

        radii.slice(0, 8).forEach((radius, ridx) => {
            const colOffset = 3 + (ridx % 2) * 38; // 2 grids per row

            if (ridx > 0 && ridx % 2 === 0) {
                currentRow += gridSize + 4;
            }

            // Grid title
            ws.mergeCells(range({ r: currentRow, c: colOffset }, { r: currentRow, c: colOffset + gridSize - 1 }));
            styleCell(ws.getCell(currentRow, colOffset), {
                value: `TANGENTIAL MOTION WITHIN THE DETECTION AREA (Movement ${radius} m)`,
                font: { bold: true, size: 10 },
                alignment: { horizontal: 'center' },
                fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE7E6E6' } }
            });

            const measurements = distanceMap.get(radius)!;

            // Create grid with pink background
            const centerRow = Math.floor(gridSize / 2);
            const centerCol = Math.floor(gridSize / 2);

            // Draw angle labels at top
            const angles = [-16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16];
            ws.getRow(currentRow + 1).height = 15;

            angles.forEach((angle, idx) => {
                const headerCol = colOffset + 8 + idx;
                styleCell(ws.getCell(currentRow + 1, headerCol), {
                    value: angle,
                    font: { size: 7, bold: true },
                    alignment: { horizontal: 'center', vertical: 'middle' }
                });
            });

            // Draw distance labels on left
            const distances = [16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
            distances.forEach((dist, idx) => {
                styleCell(ws.getCell(currentRow + 2 + idx, colOffset + 7), {
                    value: dist,
                    font: { size: 7, bold: true },
                    alignment: { horizontal: 'center', vertical: 'middle' }
                });
            });

            // Draw grid cells with detection data
            for (let row = 0; row < gridSize - 2; row++) {
                for (let col = 0; col < 17; col++) {
                    const cellRow = currentRow + 2 + row;
                    const cellCol = colOffset + 8 + col;

                    const isCenter = (row === centerRow - 1 && col === centerCol - 8);

                    // Calculate if this cell is within detection boundary
                    const distFromCenter = Math.sqrt(Math.pow(row - (centerRow - 1), 2) + Math.pow(col - (centerCol - 8), 2));
                    const inBoundary = distFromCenter <= (radius * 1.5);

                    // Find if there's a detection at this grid position
                    let detected = false;
                    const gridAngle = ((col - (centerCol - 8)) / centerCol) * 180;
                    const gridDist = Math.abs(row - (centerRow - 1)) * 0.5;

                    // Check measurements for detection
                    measurements.forEach(m => {
                        if (Math.abs(m.angle - gridAngle) < 15 && m.detected) {
                            detected = true;
                        }
                    });

                    const cell = ws.getCell(cellRow, cellCol);

                    if (isCenter) {
                        styleCell(cell, {
                            value: 'S',
                            font: { size: 7, bold: true },
                            alignment: { horizontal: 'center', vertical: 'middle' },
                            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' } }
                        });
                    } else {
                        styleCell(cell, {
                            value: detected ? '1' : '',
                            font: { size: 7 },
                            alignment: { horizontal: 'center', vertical: 'middle' },
                            fill: {
                                type: 'pattern',
                                pattern: 'solid',
                                fgColor: {
                                    argb: detected ? 'FF92D050' : (inBoundary ? 'FFFFC7CE' : 'FFFFFFFF')
                                }
                            },
                            border: {
                                top: { style: 'thin', color: { argb: 'FFD0D0D0' } },
                                left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
                                bottom: { style: 'thin', color: { argb: 'FFD0D0D0' } },
                                right: { style: 'thin', color: { argb: 'FFD0D0D0' } }
                            }
                        });
                    }

                    ws.getRow(cellRow).height = 12;
                }
            }

            // Add degree markers
            styleCell(ws.getCell(currentRow + centerRow + 1, colOffset + 4), { value: '270°', font: { size: 8 } });
            styleCell(ws.getCell(currentRow + centerRow + 1, colOffset + gridSize + 4), { value: '90°', font: { size: 8 } });
            styleCell(ws.getCell(currentRow + 1, colOffset + centerCol), { value: '0°', font: { size: 8 } });
            styleCell(ws.getCell(currentRow + gridSize + 1, colOffset + centerCol), { value: '180°', font: { size: 8 } });
        });
    }

    /**
     * Tangential Boundary Tab - Boundary measurements with detailed table
     */
    private static buildTangentialBoundary(
        wb: ExcelJS.Workbook,
        boundaryData: BoundaryMeasurement[],
        metadata: TestMetadata
    ) {
        const ws = wb.addWorksheet('Major - Tangential Boundary');
        setSheetBase(ws);

        // Set column widths
        for (let i = 3; i <= 12; i++) ws.getColumn(i).width = 15;

        addConfidentialBanner(ws);
        addBigTitle(ws, 5, 'PIR SENSOR PERFORMANCE', 'TANGENTIAL MOVEMENT BOUNDARY');

        // Calculate max boundary
        const maxBoundary = Math.max(...boundaryData.filter(b => b.distance !== null).map(b => b.distance || 0));

        // Metadata
        const metaRow = 10;
        styleCell(ws.getCell(metaRow, 3), {
            value: `Explanation of the movement boundary for the ${metadata.mountingHeight || '2.5 m'} Mounting height`,
            font: { bold: true }
        });

        ws.mergeCells(range({ r: metaRow + 1, c: 3 }, { r: metaRow + 1, c: 5 }));
        styleCell(ws.getCell(metaRow + 1, 3), {
            value: 'Calculation range acc 15 % rule *',
            font: { italic: true, size: 10 }
        });

        styleCell(ws.getCell(metaRow + 3, 3), { value: 'IP x conflict', font: { bold: true } });
        ws.mergeCells(range({ r: metaRow + 3, c: 4 }, { r: metaRow + 3, c: 5 }));
        styleCell(ws.getCell(metaRow + 3, 4), {
            value: 'x',
            fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF92D050' } },
            alignment: { horizontal: 'center' }
        });

        styleCell(ws.getCell(metaRow + 5, 3), { value: 'Swept radius', font: { bold: true } });
        styleCell(ws.getCell(metaRow + 5, 4), { value: `${maxBoundary.toFixed(1)}m` });

        styleCell(ws.getCell(metaRow + 6, 3), { value: 'Variable diameter', font: { bold: true } });
        const diameter = (Math.max(...boundaryData.map(b => b.distance || 0)) - Math.min(...boundaryData.filter(b => b.distance).map(b => b.distance || 0)));
        styleCell(ws.getCell(metaRow + 6, 4), { value: `${diameter.toFixed(1)}m` });

        // Boundary data table
        const tableStart = 25;
        const headers = [
            'Angle (°)',
            'Measurement 1\n2.5 m (m)',
            'Verdict 1\n2.5 m',
            'Specification\n(m)',
            'Measurement 1\n3 m (m)',
            'Verdict 1\n3 m'
        ];

        headers.forEach((header, i) => {
            styleCell(ws.getCell(tableStart, 3 + i), {
                value: header,
                font: { bold: true, size: 10 },
                alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
                fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFCD5B4' } },
                border: {
                    top: { style: 'thin' },
                    left: { style: 'thin' },
                    bottom: { style: 'thin' },
                    right: { style: 'thin' }
                }
            });
        });
        ws.getRow(tableStart).height = 30;

        // Group by angle
        const angleMap = new Map<number, BoundaryMeasurement[]>();
        boundaryData.forEach(b => {
            if (!angleMap.has(b.angle)) angleMap.set(b.angle, []);
            angleMap.get(b.angle)!.push(b);
        });

        const angles = Array.from(angleMap.keys()).sort((a, b) => a - b);

        angles.forEach((angle, i) => {
            const r = tableStart + 1 + i;
            const measurements = angleMap.get(angle)!;
            const avgDistance = measurements.reduce((sum, m) => sum + (m.distance || 0), 0) / measurements.length;
            const detected = measurements.some(m => m.detected);

            styleCell(ws.getCell(r, 3), { value: angle });
            styleCell(ws.getCell(r, 4), {
                value: avgDistance > 0 ? avgDistance : 0,
                numFmt: '0.0'
            });
            styleCell(ws.getCell(r, 5), {
                value: detected ? 'x' : '',
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: detected ? 'FF92D050' : 'FFFFFFFF' }
                },
                alignment: { horizontal: 'center' }
            });
            styleCell(ws.getCell(r, 6), { value: 0, numFmt: '0.0' });
            styleCell(ws.getCell(r, 7), {
                value: avgDistance > 0 ? avgDistance : 0,
                numFmt: '0.0'
            });
            styleCell(ws.getCell(r, 8), {
                value: detected ? 'x' : '',
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: detected ? 'FF92D050' : 'FFFFFFFF' }
                },
                alignment: { horizontal: 'center' }
            });

            // Add borders
            for (let col = 3; col <= 8; col++) {
                ws.getCell(r, col).border = {
                    top: { style: 'thin' },
                    left: { style: 'thin' },
                    bottom: { style: 'thin' },
                    right: { style: 'thin' }
                };
            }
        });
    }

    /**
     * Radial Tab - Radial motion measurements
     */
    private static buildRadial(
        wb: ExcelJS.Workbook,
        radialData: RadialMeasurement[],
        metadata: TestMetadata
    ) {
        const ws = wb.addWorksheet('Major - Radial');
        setSheetBase(ws);

        for (let i = 3; i <= 12; i++) ws.getColumn(i).width = 12;

        addConfidentialBanner(ws);
        addBigTitle(ws, 5, 'PIR SENSOR PERFORMANCE', 'RADIAL MOTION');

        // Metadata section
        const metaRow = 10;
        addMetaBlock(ws, metaRow, [
            { label: 'Product', value: metadata.sensorId },
            { label: 'Test lab', value: metadata.testLab || 'H.E.A.T. Bot' },
            { label: 'Test protocol', value: metadata.testMethod || 'IEC 63180 automated' },
            { label: 'Test person', value: metadata.operator || 'H.E.A.T. Bot' },
            { label: 'Description EUT', value: metadata.testChoiceName || 'PIR Sensor' },
            { label: 'Date', value: metadata.startTime.toLocaleDateString() },
            { label: 'Manufacturer', value: 'N/A' },
            { label: 'HW version', value: metadata.hwVersion || 'N/A' },
            { label: 'SW version', value: metadata.swVersion || 'N/A' },
            { label: 'Mounting height', value: metadata.mountingHeight || '2.5 m - 3 m' }
        ]);

        styleCell(ws.getCell(metaRow + 11, 3), { value: 'Room temperature', font: { bold: true } });
        styleCell(ws.getCell(metaRow + 11, 4), {
            value: metadata.temperature ? `${metadata.temperature.toFixed(1)}°C` : 'N/A'
        });

        styleCell(ws.getCell(metaRow + 12, 3), { value: 'Test person', font: { bold: true } });
        styleCell(ws.getCell(metaRow + 12, 4), { value: metadata.operator || 'H.E.A.T. Bot' });

        // Radial data table
        const tableStart = 30;
        const headers = [
            'Angle (°)',
            'Measurement 1\n2.5 m (m)',
            'Measurement 2\n2.5 m (m)',
            'Specification\n(m)',
            'Verdict\ndetection\n2.5 m',
            'Measurement 1\n3 m (m)',
            'Measurement 2\n3 m (m)',
            'Verdict\n3 m',
            'Verdict\n3.2 m'
        ];

        headers.forEach((header, i) => {
            styleCell(ws.getCell(tableStart, 3 + i), {
                value: header,
                font: { bold: true, size: 9 },
                alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
                fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFCD5B4' } }
            });
        });
        ws.getRow(tableStart).height = 40;

        // Group by angle
        const angleMap = new Map<number, RadialMeasurement[]>();
        radialData.forEach(r => {
            if (!angleMap.has(r.angle)) angleMap.set(r.angle, []);
            angleMap.get(r.angle)!.push(r);
        });

        const angles = Array.from(angleMap.keys()).sort((a, b) => a - b);

        angles.forEach((angle, i) => {
            const r = tableStart + 1 + i;
            const measurements = angleMap.get(angle)!;
            const avgDistance = measurements.reduce((sum, m) => sum + m.distance, 0) / measurements.length;
            const detected = measurements.some(m => m.detected);

            styleCell(ws.getCell(r, 3), { value: angle });
            styleCell(ws.getCell(r, 4), { value: avgDistance, numFmt: '0.0' });
            styleCell(ws.getCell(r, 5), { value: avgDistance, numFmt: '0.0' });
            styleCell(ws.getCell(r, 6), { value: 0, numFmt: '0.0' });
            styleCell(ws.getCell(r, 7), {
                value: detected ? 'x' : '',
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: detected ? 'FF92D050' : 'FFFFC7CE' }
                },
                alignment: { horizontal: 'center' }
            });
            styleCell(ws.getCell(r, 8), { value: avgDistance, numFmt: '0.0' });
            styleCell(ws.getCell(r, 9), { value: avgDistance, numFmt: '0.0' });
            styleCell(ws.getCell(r, 10), {
                value: detected ? 'x' : '',
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: detected ? 'FF92D050' : 'FFFFC7CE' }
                },
                alignment: { horizontal: 'center' }
            });
            styleCell(ws.getCell(r, 11), {
                value: detected ? 'x' : '',
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: detected ? 'FF92D050' : 'FFFFC7CE' }
                },
                alignment: { horizontal: 'center' }
            });

            for (let col = 3; col <= 11; col++) {
                ws.getCell(r, col).border = {
                    top: { style: 'thin' },
                    left: { style: 'thin' },
                    bottom: { style: 'thin' },
                    right: { style: 'thin' }
                };
            }
        });
    }

    /**
     * Cell Count Tab - Detailed statistics per radius
     */
    private static buildCellCount(
        wb: ExcelJS.Workbook,
        tangentialData: TangentialMeasurement[]
    ) {
        const ws = wb.addWorksheet('Cell count - Tangential grid');
        setSheetBase(ws);

        for (let i = 3; i <= 10; i++) ws.getColumn(i).width = 12;

        addConfidentialBanner(ws);
        addBigTitle(ws, 5, 'CELL COUNT', 'TANGENTIAL GRID VALIDATION (15% RULE)');

        // Group by distance
        const distanceMap = new Map<number, TangentialMeasurement[]>();
        tangentialData.forEach(t => {
            const dist = Math.round(t.distance);
            if (!distanceMap.has(dist)) distanceMap.set(dist, []);
            distanceMap.get(dist)!.push(t);
        });

        const distances = Array.from(distanceMap.keys()).sort((a, b) => a - b);

        // Explanation
        ws.mergeCells(range({ r: 8, c: 3 }, { r: 8, c: 10 }));
        styleCell(ws.getCell(8, 3), {
            value: 'IEC 63180 requires 85% detection rate within coverage area (15% tolerance)',
            font: { italic: true, size: 10 }
        });

        // Table
        const tableStart = 11;
        const headers = ['Radius (m)', '# cells', '# cells OK', 'Detection Rate', 'Allowed NOK (15%)', 'Status'];

        headers.forEach((header, i) => {
            styleCell(ws.getCell(tableStart, 3 + i), {
                value: header,
                font: { bold: true },
                alignment: { horizontal: 'center', vertical: 'middle' },
                fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFD9E1F2' } }
            });
        });

        distances.forEach((dist, i) => {
            const r = tableStart + 1 + i;
            const measurements = distanceMap.get(dist)!;
            const total = measurements.length;
            const detected = measurements.filter(m => m.detected).length;
            const rate = (detected / total) * 100;
            const allowedFail = Math.ceil(total * 0.15);
            const passes = rate >= 85;

            styleCell(ws.getCell(r, 3), { value: dist });
            styleCell(ws.getCell(r, 4), { value: total });
            styleCell(ws.getCell(r, 5), { value: detected });
            styleCell(ws.getCell(r, 6), { value: rate, numFmt: '0.0"%"' });
            styleCell(ws.getCell(r, 7), { value: allowedFail });
            styleCell(ws.getCell(r, 8), {
                value: passes ? 'PASS' : 'FAIL',
                font: { bold: true },
                fill: {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: passes ? 'FF92D050' : 'FFFFC7CE' }
                },
                alignment: { horizontal: 'center' }
            });

            for (let col = 3; col <= 8; col++) {
                ws.getCell(r, col).border = {
                    top: { style: 'thin' },
                    left: { style: 'thin' },
                    bottom: { style: 'thin' },
                    right: { style: 'thin' }
                };
            }
        });
    }
}
